@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Figures.Figure",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_805530095 { 
   	label=Figures
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Circle805530095[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Circle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   r: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ S()</TD></TR>
<TR><TD ALIGN="LEFT" >+ drawCircle(dOval: Circle, cOval: Graphics)</TD></TR>
<TR><TD ALIGN="LEFT" >+ move()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Cub805530095[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cub</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   dlinaRedra: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ S()</TD></TR>
<TR><TD ALIGN="LEFT" >+ move()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Figure805530095[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Figure</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   dx: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   dy: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   x: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   y: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ S()</TD></TR>
<TR><TD ALIGN="LEFT" >+ move()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Rectangle805530095[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Rectangle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   dlina: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   shirina: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ S()</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw3DRect(rect1: Rectangle, cOval: Graphics)</TD></TR>
<TR><TD ALIGN="LEFT" >+ move()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Square805530095[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Square</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   str: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ S()</TD></TR>
<TR><TD ALIGN="LEFT" >+ drawSquare(square: Square, cOval: Graphics)</TD></TR>
<TR><TD ALIGN="LEFT" >+ move()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Figure805530095 -> Circle805530095[arrowhead=none, arrowtail=empty, dir=both];
Figure805530095 -> Cub805530095[arrowhead=none, arrowtail=empty, dir=both];
Figure805530095 -> Rectangle805530095[arrowhead=none, arrowtail=empty, dir=both];
Figure805530095 -> Square805530095[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml